import fontAwesomeIcon from '@fortawesome/vue-fontawesome'
import {
  faUser,
  faAddressCard,
  faSearch,
  faNewspaper,
  faUndo,
  faArrowLeft,
  faBars,
  faExpandArrowsAlt,
  faAngleUp,
  faAngleDown,
  faCalendarAlt,
  faListAlt,
  faEnvelope,
  faFolder,
  faCalendarCheck,
  faEdit,
  faTimes,
  faCaretDown,
  faSitemap,
  faRetweet,
  faTv,
  faExternalLinkAlt,
  faPowerOff,
  faHome,
  faTable,
  faShekelSign,
  faBullhorn,
  faUsersCog,
  faUserCog,
  faCog,
  faPenSquare,
  faTrashAlt,
  faCalendarMinus,
  faBroadcastTower,
  faMoneyCheckAlt,
  faDollarSign,
  faCar,
  faChartArea,
  faBalanceScale,
  faCrown,
  faFlag,
  faStar
} from '@fortawesome/free-solid-svg-icons'

let icons = {
  faUser: faUser,
  faAddressCard: faAddressCard,
  faSearch: faSearch,
  faNewspaper: faNewspaper,
  faCalendarAlt: faCalendarAlt,
  faListAlt: faListAlt,
  faEnvelope: faEnvelope,
  faFolder: faFolder,
  faCalendarCheck: faCalendarCheck,
  faCalendarCheck: faEdit,
  faTimes: faTimes,
  faCaretDown: faCaretDown,
  faTv: faTv,
  faExternalLinkAlt: faExternalLinkAlt,
  faPowerOff: faPowerOff,
  faHome: faHome,
  faTable: faTable,
  faShekelSign: faShekelSign,
  faBullhorn: faBullhorn,
  faUsersCog: faUsersCog,
  faUserCog: faUserCog,
  faCog: faCog,
  faUndo: faUndo,
  faArrowLeft: faArrowLeft,
  faBars: faBars,
  faExpandArrowsAlt: faExpandArrowsAlt,
  faAngleUp: faAngleUp,
  faAngleDown: faAngleDown,
  faSitemap: faSitemap,
  faRetweet: faRetweet,
  faPenSquare: faPenSquare,
  faTrashAlt: faTrashAlt,
  icoonfaCalendarCheck: faCalendarCheck,
  faCalendarMinus: faCalendarMinus,
  faBroadcastTower: faBroadcastTower,
  faMoneyCheckAlt: faMoneyCheckAlt,
  faDollarSign: faDollarSign,
  faCar: faCar,
  faChartArea: faChartArea,
  faBalanceScale: faBalanceScale,
  faCrown: faCrown,
  faFlag: faFlag,
  faStar: faStar

};


export default icons