const AUTH = {
  SET: "AUTH_SET"
};

const USER_ACTION = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  REMOVE_CURRENT_USER: "REMOVE_CURRENT_USER",
  SET_USER_OPTIONS: "SET_USER_OPTIONS",
  SET_URL: "SET_URL"
};

const GRID_FILTER = {
  SET: "GRID_PARAM_SET",
  RESET: "GRID_FILTER_RESET",
  RELOAD: "GRID_FILTER_RELOAD",
  QUERY: "GRID_FILTER_QUERY",
  SET_PARAMS: "GRID_FILTER_SET_PARAMS",
  SET_CONDITION: "SET_CONDITION",
  SET_MULIT: "SET_MULIT",
  CLEAR_MULIT: "CLEAR_MULIT"
};

const FORM_lAYOUT = {
  EL_SET: "EL_SET",
  EL_ADD: "EL_ADD",
  EL_REMOVE: "EL_REMOVE",
  EL_UPDATE: "EL_UPDATE",
  EL_UPDATE_INDEX: "EL_UPDATE_INDEX",
  EL_SHOW_SET: "EL_SHOW_SET",
  EL_SET_CURRENT: "EL_SET_CURRENT",
  EL_RESET: "EL_RESET",
  EL_SUB_ADD: "EL_SUB_ADD",
  EL_SUB_REMOVE: "EL_SUB_REMOVE",
  EL_SUB_SET: "EL_SUB_SET"
};

const SEL_USER = {
  SET: "SEL_USER_SET",
  RESET: "SEL_USER_RESET",
  ADD: "SEL_USER_ADD",
  REMOVE: "SEL_USER_REMOVE",
  CANCEL: "SEL_USER_CANCEL",
  REMOVEALL: "SEL_USER_REMOVE_ALL",
  QUERY: "SEL_USER_QUERY"
};

const ATTACHMENT = {
  SET_STATUS: "SET_STATUS"
};
const FLOW_WORK = {
  SET: "FLOW_WORK_SET",
  BeValidateSET: "FLOW_WORK_BeValidateSET"
};
export {
  AUTH,
  USER_ACTION,
  GRID_FILTER,
  FORM_lAYOUT,
  SEL_USER,
  ATTACHMENT,
  FLOW_WORK
};
